---
title: "Parametric Bootstrapping"
author: "CJ Carani, Dylan Hunt and Matt Kaznikov"
date: "02-21-2024"
output: pdf_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, fig.height = 3, fig.width = 6)
library(tidyverse)
library(GGally)
library(knitr)
library(gridExtra)
library(MASS)
library(gridExtra)  
library(mnormt) 
library(lme4) 
library(lmerTest)
library(knitr) 
library(kableExtra)
library(tidyverse)
library(Matrix)
```

Data for a model with many observations and varaibles (Airbnb)
```{r}
Airbnb <- read_csv("https://raw.githubusercontent.com/proback/BeyondMLR/master/data/airbnb.csv")
```

```{r}
M1 <- lm(price ~ bedrooms + WalkScore + TransitScore + BikeScore, data = Airbnb)
summary(M1)

```
```{r}
M2 <- lmer(data = Airbnb, price ~ BikeScore + WalkScore + TransitScore + (1|neighborhood))
summary(M2)

```
```{r}
# Record estimates from the original model (M1)
b0 <- coef(M)[1]
b1 <- coef(M)[2]
sigma <- summary(M1)$sigma
nreps <- 10000

# Initialize vectors for bootstrap results
bootstrap_b0 <- numeric(nreps)
bootstrap_b1 <- numeric(nreps)
bootstrap_sigma <- numeric(nreps)

# Copy the original data for simulation
B_Data <- Airbnb

# Simulate data and fit model
for (i in 1:nreps) {
  # Simulate new data
  B_Data$SimPrice <- b0 + b1 * B_Data$bedrooms + rnorm(n = nrow(Airbnb), mean = 0, sd = sigma)
  
  # Fit model to simulated data
  Mb <- lm(SimPrice ~ bedrooms, data = B_Data)
  
  # Record coefficients and sigma from the model on simulated data
  bootstrap_b0[i] <- coef(Mb)[1]
  bootstrap_b1[i] <- coef(Mb)[2]
  bootstrap_sigma[i] <- summary(Mb)$sigma
}

# Create a data frame with bootstrap results
Bootstrap_Results <- data.frame(bootstrap_b0, bootstrap_b1, bootstrap_sigma)

# View the summary of bootstrap results
summary(Bootstrap_Results)


```
```{r}
# Load necessary libraries
library(lme4)

# Original model M2
M2 <- lmer(price ~ BikeScore + WalkScore + TransitScore + (1|neighborhood), data = Airbnb)

# Record estimates from the original model
b0 <- fixef(M2)[1]
b1 <- fixef(M2)[2]
sigma <- summary(M2)$sigma
nreps <- 10000

# Initialize vectors for bootstrap results
bootstrap_b0 <- numeric(nreps)
bootstrap_b1 <- numeric(nreps)
bootstrap_sigma <- numeric(nreps)

# Copy the original data for simulation
B_Data <- Airbnb

# Simulate data and fit model
for (i in 1:nreps) {
  # Simulate new data
  B_Data$SimPrice <- b0 + b1 * B_Data$WalkScore + rnorm(n = nrow(Airbnb), mean = 0, sd = sigma)
  
  # Fit mixed-effects model to simulated data
  Mb <- lmer(SimPrice ~ WalkScore + (1|neighborhood), data = B_Data)
  
  # Record fixed effects and sigma from the model on simulated data
  bootstrap_b0[i] <- fixef(Mb)[1]
  bootstrap_b1[i] <- fixef(Mb)[2]
  bootstrap_sigma[i] <- summary(Mb)$sigma
}

# Create a data frame with bootstrap results
Bootstrap_Results_M2 <- data.frame(bootstrap_b0, bootstrap_b1, bootstrap_sigma)

# View the summary of bootstrap results
summary(Bootstrap_Results_M2)


```


<<<<<<< HEAD
=======
Use the Airbnb to compare models
maybe llsr vs lme?
```{r}
#llsr model
m1 <- lm(data = Airbnb, price ~ BikeScore + WalkScore + TransitScore)

#lme model
m2 <- lmer(data = Airbnb, price ~ BikeScore + WalkScore + TransitScore + (1|neighborhood))
```

Data for a model without many observations (Elephants)

```{r}
elephants <- read_csv("https://raw.githubusercontent.com/proback/BeyondMLR/master/data/elephant.csv")
```

```{r}
E_M1 <- lm(MATINGS ~ AGE, data = elephants)
summary(E_M1)

elephants <- elephants %>% mutate(age2 = AGE*AGE)
E_M2 <- lm(MATINGS ~ AGE + age2, data = elephants)
summary(E_M2)
```
#Bootstrap for Model 1 Estimates
```{r}
# record estimates from the model
b0 <- E_M1$coefficients[1]
b1 <- E_M1$coefficients[2]
sigma <- summary(E_M1)$sigma
nreps <- 10000
bootstrap_b0 <- c(rep(NA, nreps))
bootstrap_b1 <- c(rep(NA, nreps))
bootstrap_sigma <- c(rep(NA, nreps))
E_Data <- elephants
# simulate data and fit model
for (i in 1:nreps){
   # simulate new data
E_Data <- E_Data %>% mutate(SimMatings = b0 + b1*AGE + rnorm(n= nrow(elephants), mean=0, sd=sigma))
Mb <- lm(data=E_Data, SimMatings~AGE)   #fit model to simulated data
bootstrap_b0[i] <- Mb$coefficients[1]        #record b0 from model on simulated data
bootstrap_b1[i] <- Mb$coefficients[2]        #record b1 from model on simulated data
bootstrap_sigma[i] <- summary(Mb)$sigma      #record sigma from model on simulated data
}
Bootstrap_Results <- data.frame(bootstrap_b0, bootstrap_b1, bootstrap_sigma)
```

```{r}
p1 <- ggplot(data=Bootstrap_Results, aes(x=bootstrap_b1)) + geom_histogram() + geom_vline(xintercept=quantile(bootstrap_b1, c(.025, .975)), color="red")
p1
```

```{r}
quantile(bootstrap_b1, c(.025, .975))
```

```{r}
# record estimates from the model
b0 <- E_M2$coefficients[1]
b1 <- E_M2$coefficients[2]
b2 <- E_M2$coefficients[3]
sigma <- summary(E_M2)$sigma
nreps <- 10000
bootstrap_b0 <- c(rep(NA, nreps))
bootstrap_b1 <- c(rep(NA, nreps))
bootstrap_b2 <- c(rep(NA, nreps))
bootstrap_sigma <- c(rep(NA, nreps))
E_Data <- elephants
# simulate data and fit model
for (i in 1:nreps){
   # simulate new data
E_Data <- E_Data %>% mutate(SimMatings = b0 + b1*AGE + b2*age2 + rnorm(n= nrow(elephants), mean=0, sd=sigma))
Mb <- lm(data=E_Data, SimMatings~AGE)        #fit model to simulated data
bootstrap_b0[i] <- Mb$coefficients[1]        #record b0 from model on simulated data
bootstrap_b1[i] <- Mb$coefficients[2]        #record b1 from model on simulated data
bootstrap_b2[i] <- Mb$coefficients[3]        #record b2 from model on simulated data
bootstrap_sigma[i] <- summary(Mb)$sigma      #record sigma from model on simulated data
}
Bootstrap_Results <- data.frame(bootstrap_b0, bootstrap_b1, bootstrap_b2, bootstrap_sigma)
```

```{r}
quantile(bootstrap_b2, c(.025, .975))
```

```{r}
anova(E_M1, E_M2)
```


```{r}
set.seed(02272022)
# record estimates from reduced model
b0 <- E_M1$coefficients[1]
b1 <- E_M1$coefficients[2]
sigma <- summary(E_M1)$sigma
nreps <- 10000
bootstrap_F <- c(rep(NA, nreps))
B_Data <- elephants
# simulate data and fit model
for (i in 1:nreps){
   # simulate new data from reduced model
B_Data <- B_Data %>% mutate(SimMatings = b0 + b1*AGE + rnorm(n= nrow(elephants), mean=0, sd=sigma))
Mb_Red <- lm(data=B_Data, SimMatings~AGE)   #fit reduced model to simulated data
Mb_Full <- lm(data=B_Data, SimMatings ~ AGE + age2)   #fit full model to simulated data
bootstrap_F[i] <- anova(Mb_Full, Mb_Red)$F[2]
}
Bootstrap_Results <- data.frame(bootstrap_F)
```

```{r}
p1 <- ggplot(data=Bootstrap_Results, aes(x=bootstrap_F)) + geom_histogram() + geom_vline(xintercept = 0.4187, color="red", linetype="dotted", size=2) 
p1
```



GLME bootstrapping
=======
# Background

# Data

# Methods

# Results

# Conclusions
